### ISSUE TITLE
Not detecting windows xp professional

### ISSUE THREAD

**Issue by aseques** [HynekPetrak/detect_bluekeep.py#4]
I found out three machines with similar characteristics not being detected, the three of them are windows xp professional (sigh..)
The log I am getting while in debug mode is this:

> python3 detect_bluekeep.py -d 10.33.25.141
> 2019-06-06 15:06:18,757 'Starting detect_bluekeep.py 0.7'
> 2019-06-06 15:06:18,758 'detect_bluekeep.py -d 10.33.25.141'
> 2019-06-06 15:06:18,758 'Going to scan 1 hosts, in 300 parallel tasks'
> 2019-06-06 15:06:18,788 '[D] [10.33.25.141] Verifying RDP protocol...'
> 2019-06-06 15:06:18,877 "Received: b'0300000b' to_receive: 000b"
> 2019-06-06 15:06:18,877 "Received data: b'0300000b06d00000123400'"
> 2019-06-06 15:06:18,877 '[D] [10.33.25.141] RDP connection accepted by the server.'
> 2019-06-06 15:06:18,878 '[D] [10.33.25.141] Starting TLS'
> 2019-06-06 15:06:18,908 '[D] [10.33.25.141] Exception: [Errno 104] Connection reset by peer'
> 2019-06-06 15:06:18,908 '[-] [10.33.25.141] Status: UNKNOWN'
>

**Comment by HynekPetrak** [comment]
Please retest, not it will not try to use TLS for WinXP

**Comment by aseques** [comment]
It works now, thanks!
